//! lock binds apko's two-architecture package lock to the declaration and
//! local trees, and records the form versions and OCI digests it resolved.
//! See docs/design/manifest.md.

const std = @import("std");
const forms = @import("form");
const compose = @import("compose");
const native = @import("build.zig");
const packages = @import("packages.zig");
const Io = std.Io;
const Dir = Io.Dir;
const Allocator = std.mem.Allocator;
const Sha256 = std.crypto.hash.sha2.Sha256;

pub const Image = struct {
    form: []const u8,
    service: []const u8,
    ref: []const u8,
    digest: []const u8,
};
pub const Form = struct { name: []const u8, serial: []const u8, local: ?[]const u8 = null };
pub const Request = struct { inputs: []const u8, images: []const Image };
pub const Record = struct {
    version: u32 = 1,
    inputs: []const u8,
    app: ?[]const u8,
    forms: []const Form,
    images: []const Image,
    requested: ?Request = null,
};

pub fn path(gpa: Allocator, s: native.Spec) ![]const u8 {
    return gpa.print("build/lock/{s}{s}{s}.lock.json", .{
        std.fs.path.basename(std.mem.trimEnd(u8, s.form, "/")),
        if (s.dev) "-dev" else "",
        if (s.published) "-published" else "",
    });
}

/// frame makes concatenation unambiguous, even for file bytes containing NUL.
fn frame(h: *Sha256, bytes: []const u8) void {
    var size: [8]u8 = undefined;
    std.mem.writeInt(u64, &size, bytes.len, .little);
    h.update(&size);
    h.update(bytes);
}

/// tree hashes sorted paths, kinds, permissions, symlink targets and bytes.
/// It never follows a symlink in the tree, nor depends on mtimes or its location.
pub fn tree(io: Io, gpa: Allocator, root: Dir, name: []const u8) ![64]u8 {
    var h = Sha256.init(.{});
    var dir = root.openDir(io, name, .{ .iterate = true }) catch |err| switch (err) {
        error.FileNotFound => {
            frame(&h, "absent");
            return std.fmt.bytesToHex(h.finalResult(), .lower);
        },
        else => return err,
    };
    defer dir.close(io);
    var paths: std.ArrayList([]const u8) = .empty;
    try paths.append(gpa, ".");
    var walker = try dir.walk(gpa);
    defer walker.deinit();
    while (try walker.next(io)) |entry| try paths.append(gpa, try gpa.dupe(u8, entry.path));
    std.mem.sort([]const u8, paths.items, {}, struct {
        fn less(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.less);
    for (paths.items) |p| {
        const st = try dir.statFile(io, p, .{ .follow_symlinks = false });
        frame(&h, p);
        frame(&h, @tagName(st.kind));
        var mode: [4]u8 = undefined;
        std.mem.writeInt(u32, &mode, @intCast(st.permissions.toMode() & 0o7777), .little);
        frame(&h, &mode);
        switch (st.kind) {
            .directory => {},
            .sym_link => {
                var buf: [4096]u8 = undefined;
                frame(&h, buf[0..try dir.readLink(io, p, &buf)]);
            },
            .file => {
                var file = try dir.openFile(io, p, .{});
                defer file.close(io);
                var content = Sha256.init(.{});
                var buf: [64 << 10]u8 = undefined;
                while (true) {
                    const n = file.readStreaming(io, &.{&buf}) catch |err| switch (err) {
                        error.EndOfStream => break,
                        else => return err,
                    };
                    if (n == 0) break;
                    content.update(buf[0..n]);
                }
                frame(&h, &content.finalResult());
            },
            else => return error.UnsupportedLockInput,
        }
    }
    return std.fmt.bytesToHex(h.finalResult(), .lower);
}

fn formHash(io: Io, gpa: Allocator, dir: []const u8) ![64]u8 {
    var h = Sha256.init(.{});
    const yaml = try gpa.print("{s}/form.yaml", .{dir});
    var text = try Dir.cwd().readFileAlloc(io, yaml, gpa, .limited(256 << 10));
    // Generated comments record the invocation, not the declaration.
    // Create and apply may spell the same inputs differently.
    if (std.mem.startsWith(u8, text, "# Generated by howl")) {
        while (text.len > 0 and (text[0] == '#' or text[0] == '\n')) {
            const end = std.mem.findScalar(u8, text, '\n') orelse break;
            text = text[end + 1 ..];
        }
    }
    frame(&h, text);
    frame(&h, &try tree(io, gpa, Dir.cwd(), try gpa.print("{s}/rootfs", .{dir})));
    return std.fmt.bytesToHex(h.finalResult(), .lower);
}

/// inputs hashes only caller-owned inputs. Published forms are outputs of
/// resolution, whose serials the lock pins; their cache paths are not inputs.
pub fn inputs(io: Io, gpa: Allocator, s: native.Spec) ![64]u8 {
    var h = Sha256.init(.{});
    frame(&h, std.fmt.comptimePrint("werewolf-lock-1-format{d}", .{compose.format}));
    frame(&h, if (s.dev) "dev" else "prod");
    frame(&h, if (s.published) "published" else "local");
    frame(&h, s.form);
    if (s.published) {
        if (std.mem.findScalar(u8, s.form, '/') != null)
            frame(&h, &try formHash(io, gpa, s.form));
    } else {
        var why: forms.Failure = .{};
        const chain = try forms.chain(io, gpa, Dir.cwd(), s.form, &why);
        for (chain) |fm| {
            frame(&h, fm.name);
            frame(&h, &try formHash(io, gpa, fm.dir));
        }
    }
    if (s.app) |app| frame(&h, &try tree(io, gpa, Dir.cwd(), app));
    return std.fmt.bytesToHex(h.finalResult(), .lower);
}

pub fn read(gpa: Allocator, text: []const u8) ?Record {
    const doc = std.json.parseFromSliceLeaky(struct { werewolf: Record }, gpa, text, .{
        .ignore_unknown_fields = true,
    }) catch return null;
    return if (doc.werewolf.version == 1) doc.werewolf else null;
}

/// matching also checks forms which fell back to the checkout because no
/// published package existed. Editing one must invalidate a published lock.
pub fn matching(io: Io, gpa: Allocator, s: native.Spec) !?Record {
    const text = Dir.cwd().readFileAlloc(io, try path(gpa, s), gpa, .limited(64 << 20)) catch |err|
        switch (err) {
            error.FileNotFound => return null,
            else => return err,
        };
    const rec = read(gpa, text) orelse return null;
    if (!std.mem.eql(u8, rec.inputs, &try inputs(io, gpa, s))) return null;
    for (rec.forms) |fm| if (fm.local) |dir| {
        const hash = formHash(io, gpa, dir) catch return null;
        if (!std.mem.eql(u8, fm.serial, &hash)) return null;
    };
    return rec;
}

pub fn formPins(gpa: Allocator, rec: Record) ![]const []const u8 {
    var pins: std.ArrayList([]const u8) = .empty;
    for (rec.forms) |fm| if (fm.local == null)
        try pins.append(gpa, try gpa.print("{s}-form={s}", .{ fm.name, fm.serial }));
    return pins.items;
}

pub fn pinned(
    images: []const Image,
    form: []const u8,
    service: []const u8,
    ref: []const u8,
) ?[]const u8 {
    for (images) |im| if (std.mem.eql(u8, im.form, form) and
        std.mem.eql(u8, im.service, service) and std.mem.eql(u8, im.ref, ref)) return im.digest;
    return null;
}

/// write widens an apko lock after all its inputs resolve successfully.
/// keep preserves its mtime when identical; failed resolution leaves the old lock.
pub fn write(b: *native.B, target: []const u8, apko: []const u8, fingerprint: []const u8) !void {
    var records: std.ArrayList(Form) = .empty;
    for (b.chain) |fm| {
        const published = for (b.from_repo) |name| {
            if (std.mem.eql(u8, name, fm.name)) break true;
        } else false;
        const serial = if (published)
            try b.read(
                try b.path("{s}/.{s}.version", .{ std.fs.path.dirname(fm.dir).?, fm.name }),
                256,
            )
        else
            try b.gpa.dupe(u8, &try formHash(b.io, b.gpa, fm.dir));
        try records.append(
            b.gpa,
            .{ .name = fm.name, .serial = serial, .local = if (published) null else fm.dir },
        );
    }
    const rec: Record = .{
        .inputs = fingerprint,
        .app = if (b.spec.app) |app|
            try b.gpa.dupe(u8, &try tree(b.io, b.gpa, Dir.cwd(), app))
        else
            null,
        .forms = records.items,
        .images = b.resolved_images.items,
        .requested = if (Dir.cwd().readFileAlloc(
            b.io,
            try b.path("{s}/.request.json", .{b.spec.form}),
            b.gpa,
            .limited(1 << 20),
        )) |text|
            try std.json.parseFromSliceLeaky(Request, b.gpa, text, .{})
        else |_|
            null,
    };
    var doc = try std.json.parseFromSliceLeaky(std.json.Value, b.gpa, apko, .{});
    if (doc != .object) return error.InvalidLock;
    const value = try std.json.parseFromSliceLeaky(
        std.json.Value,
        b.gpa,
        try std.json.Stringify.valueAlloc(b.gpa, rec, .{}),
        .{},
    );
    try doc.object.put(b.gpa, "werewolf", value);
    const text = try std.json.Stringify.valueAlloc(b.gpa, doc, .{ .whitespace = .indent_2 });
    try packages.keep(b, target, try b.path("{s}\n", .{text}));
}

test "tree binds bytes, names, links and modes, independent of creation order" {
    const t = std.testing;
    const io = t.io;
    var arena: std.heap.ArenaAllocator = .init(t.allocator);
    defer arena.deinit();
    const gpa = arena.allocator();
    var tmp = t.tmpDir(.{});
    defer tmp.cleanup();
    try tmp.dir.createDirPath(io, "a");
    try tmp.dir.createDirPath(io, "b");
    try tmp.dir.writeFile(io, .{ .sub_path = "a/x", .data = "one" });
    try tmp.dir.writeFile(io, .{ .sub_path = "a/y", .data = "two" });
    try tmp.dir.writeFile(io, .{ .sub_path = "b/y", .data = "two" });
    try tmp.dir.writeFile(io, .{ .sub_path = "b/x", .data = "one" });
    const original = try tree(io, gpa, tmp.dir, "a");
    try t.expectEqualStrings(&original, &try tree(io, gpa, tmp.dir, "b"));
    try tmp.dir.writeFile(io, .{ .sub_path = "b/x", .data = "new" });
    try t.expect(!std.mem.eql(u8, &original, &try tree(io, gpa, tmp.dir, "b")));
    try tmp.dir.deleteFile(io, "a/y");
    try t.expect(!std.mem.eql(u8, &original, &try tree(io, gpa, tmp.dir, "a")));
    try tmp.dir.symLink(io, "missing", "a/link", .{});
    const link = try tree(io, gpa, tmp.dir, "a");
    try tmp.dir.deleteFile(io, "a/link");
    try tmp.dir.symLink(io, "elsewhere", "a/link", .{});
    try t.expect(!std.mem.eql(u8, &link, &try tree(io, gpa, tmp.dir, "a")));
}
