#!/bin/sh
# forms/blocky/test/config DIR: the blocky form's config for make check, in
# DIR: one upstream and one blocklist, which test/checks finds in the
# configuration Blocky runs.
set -eu
mkdir -p "$1/blocky"
echo '{"upstreams":["tcp-tls:dns.quad9.net"],"blocklists":["https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"]}' >"$1/blocky/settings.json"
